/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
  queries:
    | { key: "posts"; input: never; result: Post[] }
    | { key: "version"; input: never; result: string };
  mutations:
    | { key: "createPost"; input: CreatePostInput; result: Post }
    | { key: "deletePost"; input: DeletePostInput; result: null };
  subscriptions: never;
};

export type Post = { id: number; title: string; content: string };

export type DeletePostInput = { id: number };

export type CreatePostInput = { title: string; content: string };
